---
- name: Deploy a jar file
  hosts: all
#   remote_user: root
  tasks:
#     - name: Installing java11 package
#       apt:
#         name: openjdk-11-jdk
#         state: present
    - name: pull docker image
      docker_image:
        name: umairbeig/junit-devops
        source: pull
      
