---
- name: Deploy a jar file
  hosts: all
  remote_user: root
  tasks:
    - name: Installing java11 package
      apt:
        name: openjdk-11-jdk
        state: present
    - name: Copy jar file to home directory
      copy:
        src: ./target/mini_project-1.0-SNAPSHOT.jar
        dest: ~/
        mode: '0755'
