---
- name: Deploy a jar file
  hosts: all
  vars:

  tasks:
    - name: pull docker image
      docker_image:
        name: umairbeig/junit-devops:latest
        source: pull

    - name: make a container
      docker_container:
         name: containerxxx
         image: umairbeig/junit-devops:latest
         state: present
         tty: true
         interactive: true



      
